### ISSUE TITLE
generating a wheel

### ISSUE THREAD

**Issue by abedhammoud** [pythonic64/hover#2]
I have integrated this package into my app, and it works very well, thanks. If there are no plans to integrate into kivy, are you planning to generate a wheel to make it possible to install with  setuptools/pyproject.toml. Many thanks.

**Comment by pythonic64** [comment]
Goal is to make it a part of Kivy garden https://github.com/kivy-garden which will make it installable with
`pip install kivy-garden.hover`

Code is done, but I have to add module documentation in `kivy_garden/hover/__init__.py`, then move package to GitHub kivy-garden repository and make a release on pypi.

**Comment by abedhammoud** [comment]
Many thanks. Excellent work.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pythonic64** [comment]
Pull request to integrate `hover` package into `Kivy==3.0.0` https://github.com/kivy/kivy/pull/9248.

**Comment by abedhammoud** [comment]
Great news, thanks Filip.

Any idea when 3.0 will be out?


Kind regards | Mit freundlichen Gruessen | Meilleures salutations | Cordiali saluti

Dr. Abed Hammoud | Managing Director
Alant Health Sàrl
chemin du Grand-Pré 22, 1163 Etoy, Switzerland
M +41 79 309 2777 (EU) | +1 303 828 7922 (US)
***@***.******@***.***> | www.Alant.Health<http://www.alant.health/> |  LinkedIn<https://www.linkedin.com/in/dr-abed-hammoud/>

[cid:c0fd5cfe-2742-4dc1-ad71-f3fa9d3b7fe7]

This message is confidential and may be privileged. It is for the intended recipient only. If you are not the intended recipient, please notify the sender and delete this message from your system.


________________________________

**Comment by pythonic64** [comment]
There is no precise release date, most likely it will be during this year. You can support merging of the `hover` feature by commenting on the pull request page.

**Comment by abedhammoud** [comment]
Just did, thank you.


Kind regards | Mit freundlichen Gruessen | Meilleures salutations | Cordiali saluti

Dr. Abed Hammoud | Managing Director
Alant Health Sàrl
chemin du Grand-Pré 22, 1163 Etoy, Switzerland
M +41 79 309 2777 (EU) | +1 303 828 7922 (US)
***@***.******@***.***> | www.Alant.Health<http://www.alant.health/> |  LinkedIn<https://www.linkedin.com/in/dr-abed-hammoud/>

[cid:4c20441d-10cd-434c-8a6c-cb83ed0b2b5b]

This message is confidential and may be privileged. It is for the intended recipient only. If you are not the intended recipient, please notify the sender and delete this message from your system.


________________________________
