### ISSUE TITLE
pypi wheel?

### ISSUE THREAD

**Issue by abedhammoud** [pythonic64/hover#4]
This is an excellent package that I have been using for some time. Currently, installing with git+https doesn't work with uv. Are there any plans to build a wheel that would allow me to do uv pip install? Thanks.

**Comment by pythonic64** [comment]
I don't have experience with `uv`, but I think after package gets released to pypi, https://github.com/pythonic64/hover/issues/2#issuecomment-2266814167, then you should be able to install it as any other python package.

**Comment by abedhammoud** [comment]
Thanks. I agree with your comment above. I look forward to continue using it. Works really well for me.

**Comment by pythonic64** [comment]
To add, with my schedule being as it is, most likely that in April I'll be able to move this package to kivy-garden and release to pypi.

**Comment by abedhammoud** [comment]
Thanks Filip. I do think it should be part of Kivy. What is the chance this happens?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pythonic64** [comment]
Sorry for the late response.

It's unlikely to be part of Kivy unless it gets a large support from the developers using it. This library is just one implementation of the hover manager/behavior and while it works great for your project it doesn't mean that it's a good general solution.
